<?php

return [
    '/'                     => 'app/views/index.php',
    'index'                 => 'app/views/index.php',
    'login'                 => 'app/views/inicio/login.php',
    'registro'              => 'app/views/inicio/registro.php',
    'olvide_pass'           => 'app/views/inicio/olvide_pass.php',
    'dashboard'             => 'app/views/dashboard/dashboard.php',
    'seguridad'             => 'app/views/seguridad/seguridad.php',
    'historial'             => 'app/views/reportes/historial.php',
    'registros'             => 'app/views/registro/registros.php',
    'tablas_maestras'       => 'app/views/gestion/tablas_maestras.php',
    'reportes'              => 'app/views/reportes/reportes.php',
    'inventario'            => 'app/views/inventario/inventario.php',
    'soporte'               => 'app/views/soporte/soporte.php',
    'ajustes'               => 'app/views/soporte/ajustes.php',
    'respaldo'              => 'app/views/seguridad/respaldo.php',
    'solicitud_sq'          => 'app/views/registro/solicitud_sq.php',
    'resultados_laboratorio'=> 'app/views/registro/resultados_laboratorio.php',
    'formatos_aplicacion'   => 'app/views/registro/formatos_aplicacion.php',
    'gestion_usuarios'      => 'app/views/gestion/gestion_usuarios.php',
    'gestion_sustancias'    => 'app/views/gestion/gestion_sustancias.php',
    'gestion_parametros'    => 'app/views/gestion/gestion_parametros.php',
    'gestion_plantas'       => 'app/views/gestion/gestion_plantas.php',
    'salir'                 => 'app/views/salir/salir.php',

    'gt_ca_001' => 'app/views/registro/gt_ca_001.php',
    'gt_ca_002' => 'app/views/registro/gt_ca_002.php',
    'gt_ca_003' => 'app/views/registro/gt_ca_003.php',
    'gt_ca_004' => 'app/views/registro/gt_ca_004.php',
    'gt_ca_005' => 'app/views/registro/gt_ca_005.php',
    'gt_ca_006' => 'app/views/registro/gt_ca_006.php',
    'gt_ca_007' => 'app/views/registro/gt_ca_007.php',
    'gt_ca_008' => 'app/views/registro/gt_ca_008.php',
    'gt_ca_009' => 'app/views/registro/gt_ca_009.php',
    'gt_ca_010' => 'app/views/registro/gt_ca_010.php',
    'gt_ca_011' => 'app/views/registro/gt_ca_011.php',
    'gt_ca_012' => 'app/views/registro/gt_ca_012.php',
    'gt_ca_013' => 'app/views/registro/gt_ca_013.php',
    'gt_ca_014' => 'app/views/registro/gt_ca_014.php',
    'gt_ca_015' => 'app/views/registro/gt_ca_015.php',
    'gt_ca_016' => 'app/views/registro/gt_ca_016.php',
    'gt_ca_017' => 'app/views/registro/gt_ca_017.php',
    'gt_ca_018' => 'app/views/registro/gt_ca_018.php',
    'gt_ca_019' => 'app/views/registro/gt_ca_019.php',

    'mantenimiento'         => 'app/views/inicio/mantenimiento.php',

    // Controladores (sin HTML, solo lógica)
    'iniciar'               => 'app/Controllers/iniciar.php',
    'registrar'             => 'app/Controllers/registrar.php',
    'forgot_password'       => 'app/Controllers/forgot_password.php',
    'reset_password'        => 'app/views/inicio/reset_password.php',
    'enviar_reset'          => 'app/Controllers/enviar_reset.php',
    'api_profile'           => 'app/Controllers/api_profile.php',
    'api_notifications'     => 'app/Controllers/api_notifications.php',
];
